"""add_buckets_table_v3

Revision ID: 29502a86c09a
Revises: 31621c3c5d43
Create Date: 2025-12-08 01:29:55.588613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29502a86c09a'
down_revision: Union[str, Sequence[str], None] = '31621c3c5d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pennywise_buckets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('monthly_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pennywise_buckets_id'), 'pennywise_buckets', ['id'], unique=False)
    op.create_index(op.f('ix_pennywise_buckets_name'), 'pennywise_buckets', ['name'], unique=True)
    op.add_column('pennywise_categories', sa.Column('bucket_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pennywise_categories', 'pennywise_buckets', ['bucket_id'], ['id'])
    op.drop_column('pennywise_categories', 'total_amount')
    op.drop_column('pennywise_categories', 'monthly_amount')
    op.add_column('pennywise_distribution_logs', sa.Column('bucket_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('pennywise_distribution_logs_category_id_fkey'), 'pennywise_distribution_logs', type_='foreignkey')
    op.create_foreign_key(None, 'pennywise_distribution_logs', 'pennywise_buckets', ['bucket_id'], ['id'])
    op.drop_column('pennywise_distribution_logs', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pennywise_distribution_logs', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pennywise_distribution_logs', type_='foreignkey')
    op.create_foreign_key(op.f('pennywise_distribution_logs_category_id_fkey'), 'pennywise_distribution_logs', 'pennywise_categories', ['category_id'], ['id'])
    op.drop_column('pennywise_distribution_logs', 'bucket_id')
    op.add_column('pennywise_categories', sa.Column('monthly_amount', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True))
    op.add_column('pennywise_categories', sa.Column('total_amount', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pennywise_categories', type_='foreignkey')
    op.drop_column('pennywise_categories', 'bucket_id')
    op.drop_index(op.f('ix_pennywise_buckets_name'), table_name='pennywise_buckets')
    op.drop_index(op.f('ix_pennywise_buckets_id'), table_name='pennywise_buckets')
    op.drop_table('pennywise_buckets')
    # ### end Alembic commands ###
