"""add_distribution_tracking_tables

Revision ID: 31621c3c5d43
Revises: 7334c30793f8
Create Date: 2025-12-04 01:07:37.046128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31621c3c5d43'
down_revision: Union[str, Sequence[str], None] = '7334c30793f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pennywise_distribution_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('is_reverted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['pennywise_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pennywise_distribution_events_id'), 'pennywise_distribution_events', ['id'], unique=False)
    op.create_table('pennywise_distribution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['pennywise_categories.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['pennywise_distribution_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pennywise_distribution_logs_id'), 'pennywise_distribution_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pennywise_distribution_logs_id'), table_name='pennywise_distribution_logs')
    op.drop_table('pennywise_distribution_logs')
    op.drop_index(op.f('ix_pennywise_distribution_events_id'), table_name='pennywise_distribution_events')
    op.drop_table('pennywise_distribution_events')
    # ### end Alembic commands ###
