"""add_category_budget_columns

Revision ID: 7334c30793f8
Revises: 5c50308a9c5a
Create Date: 2025-12-04 00:15:32.241441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7334c30793f8'
down_revision: Union[str, Sequence[str], None] = '5c50308a9c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pennywise_categories', sa.Column('monthly_amount', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('pennywise_categories', sa.Column('total_amount', sa.Numeric(precision=20, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pennywise_categories', 'total_amount')
    op.drop_column('pennywise_categories', 'monthly_amount')
    # ### end Alembic commands ###
