"""make card fields nullable

Revision ID: 915e474e5038
Revises: c72ff25562bc
Create Date: 2025-12-03 22:55:40.309274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '915e474e5038'
down_revision: Union[str, Sequence[str], None] = 'c72ff25562bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pennywise_cards', 'card_last4',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pennywise_cards', 'bank_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pennywise_cards', 'bank_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pennywise_cards', 'card_last4',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
