"""Initial migration

Revision ID: c72ff25562bc
Revises: 
Create Date: 2025-12-03 17:59:24.682082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c72ff25562bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pennywise_account_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('account_last4', sa.String(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('is_credit_card', sa.Boolean(), nullable=True),
    sa.Column('sms_source', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pennywise_account_balances_id'), 'pennywise_account_balances', ['id'], unique=False)
    op.create_table('pennywise_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_last4', sa.String(), nullable=False),
    sa.Column('card_type', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('account_last4', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_balance', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('last_balance_source', sa.String(), nullable=True),
    sa.Column('last_balance_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pennywise_cards_id'), 'pennywise_cards', ['id'], unique=False)
    op.create_table('pennywise_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('is_income', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pennywise_categories_id'), 'pennywise_categories', ['id'], unique=False)
    op.create_index(op.f('ix_pennywise_categories_name'), 'pennywise_categories', ['name'], unique=True)
    op.create_table('pennywise_chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('isUser', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('isSystemPrompt', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pennywise_exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.String(), nullable=False),
    sa.Column('to_currency', sa.String(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at_unix', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at_unix', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pennywise_exchange_rates_id'), 'pennywise_exchange_rates', ['id'], unique=False)
    op.create_table('pennywise_import_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pennywise_import_logs_id'), 'pennywise_import_logs', ['id'], unique=False)
    op.create_table('pennywise_merchant_mappings',
    sa.Column('merchant_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('merchant_name')
    )
    op.create_table('pennywise_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_name', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('next_payment_date', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('umn', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('sms_body', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pennywise_subscriptions_id'), 'pennywise_subscriptions', ['id'], unique=False)
    op.create_table('pennywise_transaction_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('actions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_system_template', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pennywise_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('merchant_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('sms_body', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('sms_sender', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('balance_after', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('transaction_hash', sa.String(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('from_account', sa.String(), nullable=True),
    sa.Column('to_account', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pennywise_transactions_id'), 'pennywise_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_pennywise_transactions_transaction_hash'), 'pennywise_transactions', ['transaction_hash'], unique=True)
    op.create_table('pennywise_unrecognized_sms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('sms_body', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('reported', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pennywise_unrecognized_sms_id'), 'pennywise_unrecognized_sms', ['id'], unique=False)
    op.create_table('pennywise_rule_applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('rule_name', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('fields_modified', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['pennywise_transaction_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pennywise_import_row_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_log_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('account_balance_id', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('merchant_mapping_id', sa.String(), nullable=True),
    sa.Column('unrecognized_sms_id', sa.Integer(), nullable=True),
    sa.Column('chat_message_id', sa.String(), nullable=True),
    sa.Column('transaction_rule_id', sa.String(), nullable=True),
    sa.Column('rule_application_id', sa.String(), nullable=True),
    sa.Column('exchange_rate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_balance_id'], ['pennywise_account_balances.id'], ),
    sa.ForeignKeyConstraint(['card_id'], ['pennywise_cards.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['pennywise_categories.id'], ),
    sa.ForeignKeyConstraint(['chat_message_id'], ['pennywise_chat_messages.id'], ),
    sa.ForeignKeyConstraint(['exchange_rate_id'], ['pennywise_exchange_rates.id'], ),
    sa.ForeignKeyConstraint(['import_log_id'], ['pennywise_import_logs.id'], ),
    sa.ForeignKeyConstraint(['merchant_mapping_id'], ['pennywise_merchant_mappings.merchant_name'], ),
    sa.ForeignKeyConstraint(['rule_application_id'], ['pennywise_rule_applications.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['pennywise_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['pennywise_transactions.id'], ),
    sa.ForeignKeyConstraint(['transaction_rule_id'], ['pennywise_transaction_rules.id'], ),
    sa.ForeignKeyConstraint(['unrecognized_sms_id'], ['pennywise_unrecognized_sms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pennywise_import_row_logs_id'), 'pennywise_import_row_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pennywise_import_row_logs_id'), table_name='pennywise_import_row_logs')
    op.drop_table('pennywise_import_row_logs')
    op.drop_table('pennywise_rule_applications')
    op.drop_index(op.f('ix_pennywise_unrecognized_sms_id'), table_name='pennywise_unrecognized_sms')
    op.drop_table('pennywise_unrecognized_sms')
    op.drop_index(op.f('ix_pennywise_transactions_transaction_hash'), table_name='pennywise_transactions')
    op.drop_index(op.f('ix_pennywise_transactions_id'), table_name='pennywise_transactions')
    op.drop_table('pennywise_transactions')
    op.drop_table('pennywise_transaction_rules')
    op.drop_index(op.f('ix_pennywise_subscriptions_id'), table_name='pennywise_subscriptions')
    op.drop_table('pennywise_subscriptions')
    op.drop_table('pennywise_merchant_mappings')
    op.drop_index(op.f('ix_pennywise_import_logs_id'), table_name='pennywise_import_logs')
    op.drop_table('pennywise_import_logs')
    op.drop_index(op.f('ix_pennywise_exchange_rates_id'), table_name='pennywise_exchange_rates')
    op.drop_table('pennywise_exchange_rates')
    op.drop_table('pennywise_chat_messages')
    op.drop_index(op.f('ix_pennywise_categories_name'), table_name='pennywise_categories')
    op.drop_index(op.f('ix_pennywise_categories_id'), table_name='pennywise_categories')
    op.drop_table('pennywise_categories')
    op.drop_index(op.f('ix_pennywise_cards_id'), table_name='pennywise_cards')
    op.drop_table('pennywise_cards')
    op.drop_index(op.f('ix_pennywise_account_balances_id'), table_name='pennywise_account_balances')
    op.drop_table('pennywise_account_balances')
    # ### end Alembic commands ###
